# 有两个磁盘文件A和B,各存放一行字母,要求把这两个文件中的信息合并(按字母顺序排列), 输出到一个新文件C中。
# f1=open('G:/pythonfile/t3.txt','w+')
# f2=open('G:/pythonfile/t4.txt','w+')
f3=open('G:/pythonfile/t5.txt','w+')
# f1.write('tanzhenhua')
# f2.write('tianxiawushuang')
# f1.close()
# f2.close()
f1=open('G:/pythonfile/t3.txt','r')
f2=open('G:/pythonfile/t4.txt','r')
str1=f1.read()
str2=f2.read()
# print(str1)
# print(str2)
f2.close()
# str1=list(str1)
# str2=list(str2)
str3=str1+str2
str3=list(str3)
str3.sort()
s=''.join(str3)
f3.write(s)
f3=open('G:/pythonfile/t5.txt','r')
s=f3.read()
print(s)
f3.close()

